title: Computer science in a nutshell
author: Jopepato
email: joseperezparras95@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my personal page where i'll be posting awesome stuff and that :)

# social links
twitter_username: jopepato
github_username:  jopepato

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
